### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [HiraokaTakuya/apery#1]
I find that include guards like "[BOOK_HPP](https://github.com/HiraokaTakuya/apery/blob/58ba7bfa74e91b3b5c29241cf7a9fdb9e10c70d6/src/book.hpp#L1)" and "[THREAD_HPP](https://github.com/HiraokaTakuya/apery/blob/58ba7bfa74e91b3b5c29241cf7a9fdb9e10c70d6/src/thread.hpp#L1)" are too short for the safe reuse of your header files (when they belong to an application programming interface).

**Comment by HiraokaTakuya** [comment]
I think I will use prefix "APERY_" for all macros.
Thank you for pointing it out.

**Comment by HiraokaTakuya** [comment]
I added all "APERY_" prefix for all include guards at "c912352b63b051a96bf0ee0a7c1c4f71666484b7"

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/HiraokaTakuya/apery/commit/c912352b63b051a96bf0ee0a7c1c4f71666484b7).
