### ISSUE TITLE
検討モード使用の場合

### ISSUE THREAD

**Issue by ghost** [HiraokaTakuya/apery#12]
検討モードで使用の場合、ここの１０月１３日の最新じゃなく１０月７日の電王戦直前更新バージョンの使用でいいのでしょうか？
変わらないですよね？（検討モードの場合で長時間考えさせたりすることにしか使用しません）

**Comment by HiraokaTakuya** [comment]
あまり更新していないので強さに大きな違いはありませんが、常に最新版が最強な状態に保っていますので、ご自身でビルド出来る場合は最新のバージョンをお使いになると良いと思います。
最新版は現状では11月3日に更新したものですね。

**Comment by ghost** [comment]
上記誤字だらけでした
