### ISSUE TITLE
投了値

### ISSUE THREAD

**Issue by futukan** [HiraokaTakuya/apery#16]
新しいAperyダウンロードしました。
投了値の設定を変更したいのですが、どの項目が投了値でしょうか？
やねうら王でApery使わず、Apery単体で使いたいので、Aperyの方に投了値設定を追加してもらうしかないのでしょうか？

**Comment by HiraokaTakuya** [comment]
すみません、途中で投了する必要が無いと思ってそのような設定は付けていませんでした。
どういう用途で必要なのでしょうか？

**Comment by futukan** [comment]
対戦で強さ計測する場合に必要です。
投了値を１５００などに設定し、同一の設定で色んなソフト同士を自己対戦する場合に必要な項目です。
レーティング計測で時間短縮出来るので便利になります。

**Comment by HiraokaTakuya** [comment]
ちょっとすぐに対応出来ないかも知れません。(評価値がおかしく表示されるような時に誤って投了しないようにする必要があるかどうかの確認など)
可能であれば投了まで指して計測して頂けると幸いです。
対局させるソフト側で投了値が設定出来れば、エンジンが個別に対応する必要がなくて嬉しいのですが。

**Comment by futukan** [comment]
やねうら王でいうとresign valueの設定のことです。対応するかどうかは判断に委ねます。
