### ISSUE TITLE
linuxでのマニュアル

### ISSUE THREAD

**Issue by hdoi** [HiraokaTakuya/apery#2]
linux でのマニュアルを書いていただけませんか？
自分でmakeして ./apery  をした時の動作が少しおかしくて、正しい手順に従っているのかわからないからです。

一応、自分でもいろいろソースをいじって、以下の事がわかりました。
evaluate.hpp の 853行目のループが延々と行われていて、フリーズしているような感じになっていました。
apery_binariesからbook.binを同じディレクトリに置いて起動しても、同じでした。

また、windows板だと起動にさほど時間もかかりませんので、何か違う感じになっているのではと思います。
環境： ubuntu14.04

**Comment by HiraokaTakuya** [comment]
Readme.txt を更新し、bin ディレクトリを submodule として追加しました。
Linux と Windows で動作が異なるという事ではなく、
現在の最新のコードでは、Eval_Dir に設定されたディレクトリに __synthesized.bin という評価関数バイナリが存在する時のみ、高速に起動する事が出来ます。
登録された評価関数バイナリは、__synthesized.bin を作成する素となる学習データなので、そのデータから一旦 *_synthesized.bin を作成する必要があります。
bin ディレクトリに make して出来た apery を置き、 make_synthesized_eval.sh を実行して下さい。
処理はPCの性能によって数分から数十分掛かります。

**Comment by hdoi** [comment]
ありがとうございます。
無事、ubuntuでビルド出来ました。
