### ISSUE TITLE
Go command needs to parse the "searchmoves" 

### ISSUE THREAD

**Issue by ShogiNinja** [HiraokaTakuya/apery#4]
The go command currently searches all possible moves. The draft USI shogi interface for the GO command (http://www.glaurungchess.com/shogi/usi.html) recommends to have a "searchmoves" parameter. This would allow for easier implementation of analyzing games as well as an easy way to force certain opening styles. Is there any chance this can be implemented? (i can see line 174/175 in usi.cpp needs to be changed, but i am not a c++ developer).

**Comment by HiraokaTakuya** [comment]
OK, I implemented it!
Thank you for your advice!
