### ISSUE TITLE
Position::see()のattackers &= occ;について

### ISSUE THREAD

**Issue by yaneurao** [HiraokaTakuya/apery#6]
細かいことで恐縮ですが、この
https://github.com/HiraokaTakuya/apery/blob/master/src/position.cpp#L607
attackers &= occ;の場所が悪い気がします。

すでに処理した駒を除外するためにどこかにこの処理は必要ですが、この処理はここ
https://github.com/HiraokaTakuya/apery/blob/master/src/position.cpp#L591
と、nextAttacker()のKING以外を返すときにやるほうが良いように思います。

そうすると、
1) moveが駒打ちでwhileループでKINGをnextAttackers()で発見したときに、
 attackers &= occの回数が一回少なくてすみます。
2) whileループのなかにattackers &= occがあると可読性が少し良くなります。
(この処理はnextAttacker()に関連する処理なのでそちらでなされて欲しいです。)

**Comment by HiraokaTakuya** [comment]
お返事遅くなりました。
ご指摘ありがとうございます。
余裕ある時に計測などしてみます。

**Comment by yaneurao** [comment]
はい(｀･ω･´)ゞ
