### ISSUE TITLE
Apery(WCSC26)の評価関数ファイルについて

### ISSUE THREAD

**Issue by yaneurao** [HiraokaTakuya/apery#7]
Apery(WCSC26)の評価関数ファイルについて。

問題点1) kppテーブルなのですがkpp[k][p1][p2]に対して、p1==0 もしくは p2==0のときに、値がゼロにならない。(ゴミが入っている)

駒落ちのとき、BonaPiece == 0としたいので、ここにゴミが入っていると駒落ちでの局面評価がおかしくなります。ここ、ゼロで埋めていただけないでしょうか。kkpテーブルも同様にkkp[k1][k2][0]に対してゴミが入っています。

問題点2) kkpテーブルのkkp[k1][k2][p]に対して、p == e_hand_pawn-1のような0枚目の手駒に対する値が0になっていない。

実際にはこの要素は参照しませんが、ここにゴミが入っていると、assert(kkp[k1][k2][p][0] == -kkp[~k2][~k1][~p][0]);のようなassertが通らなくなってしまいます。(Squareに対して~sqは180度回転した升を返す演算子、BonaPieceに対して~pは(盤上の駒であれば180度回転させ)、相手の駒にする演算子だとします。)

問題点3) kpp[k1][p1][p2] != kpp[k1][mirror(p1)][mirror(p2)] ただし、file_of(k1) == FILE_5

玉が5筋にいるときに、kppの要素が左右のミラーに対して対称性がありません。玉が5筋以外にいるときは対称性があるので学習上の何らかのバグでノイズを入れてしまっているのではないかと思います。当然ながら、ここは対称にしたほうが棋力的にも強くなるのではないかと思います。

例) kpp[SQ_51][f_hand_pawn][f_pawn + SQ_12] != kpp[SQ_51][f_hand_pawn][f_pawn + SQ_92]
※　玉が51にいて、「先手の手駒の1枚目の歩」と、「盤上の12の歩」というkpp値が、この12の歩を92に移動させたときのものと同じ値でないといけないはずなのに、そうはなっていません。

急ぎませんので、次回、評価関数バイナリを公開されるときにでも直っていれば嬉しいです。

**Comment by HiraokaTakuya** [comment]
問題点1, 2 については、一応特に理由が無い限りにおいては0埋めしようと思います。ただ、本来は参照しないので何が入っていてもよく、評価バイナリを使う側のソフトが明示的に0にしておくのが良いと思います。
問題点3 については、バグでしたので、ご指摘ありがとうございます。
一旦は左右対称に直す事を検討いたしますが、今後もずっと左右対称にするかは未定です。

**Comment by yaneurao** [comment]
承知しました。(｀･ω･´)ゞ
