### ISSUE TITLE
Shogidokoro debug files - ShogiGUI (English translation)

### ISSUE THREAD

**Issue by ChessGUI** [HiraokaTakuya/apery#8]
Hello Hiraoka,

Apery application is very strong and beats most of its opponents!!

Could you please download ShogiGUI http://shogigui.siganus.com/ and make an English translation of all commands like new game-engine tournament-add engine etc.? 

I have some problems with the implementation of these chess engines and Shogidokoro-Interface http://www.geocities.jp/shogidokoro/download.html

Kifu Warabe 1.15 http://grayscale.iza-yoi.net/shogi/download.html  can be implemented, but before its first move appears this message: "DII Not Found Exception Unable to load dll Lua52. The specified module was not found. Exception from HRE Result 0x8007007E (annotation: previous versions show not such a behaviour, but play illegal moves) - by the way: download of lua52.dll http://api.256file.com/download/97466_lua52.dll and replace the existing lua52.dll by this file does not solve this problem - it was tried to load a file with the wrong format (Bad Image Format Exception) - a 5-min-byoyomi engine-match vs. Lesserkai 1.4.1 (built-in) or other USI Shogi software is impossible 
Debug - Windows

> C:usi
> <C:option name ? type check default true
> <C:option name USI type spin default 2 min 1 max 13
> <C:option name ? type combo default tiger var ??? var ?? var tiger var ?? var ? var ?? var ? var ??? var ???? var ??? var ??? var ????
> <C:option name ? type button default ???
> <C:option name ? type string default DRAGON
> <C:option name ? type filename default ????.html
> <C:id name KifuWarabe
> <C:id author TAKAHASHI Satoshi
> <C:usiok
> C:quit

Sjaak 1.3.1a MS x64 http://www.eglebbk.dds.nl/program/chess-download.html plays Shogi like Nebiyu 1.45 https://sites.google.com/site/dshawul/home on WinBoard GUI 4.8.0  Interface http://www.open-aurec.com/wbforum/viewtopic.php?f=19&t=51528 (WinBoard-protocol) but does not work with Shogidokoro 3.7.2 > "not an USI engine", although you can obtain this output by hand: 
# [Chess] 0w>usi

id name Sjaak II 1.3.1a (x86_64)
id author Evert Glebbeek
option name Hash type spin default 48 min 1 max 4096
option name Ponder type check default true
option name UCI_Chess960 type check default true
option name UCI_Variant type combo default shogi var chess var chess960 var seirawan var shatar var makruk var shatranj var sittuyin var crazyhouse var chessgi var asean var ai-wok var super var spartan var pocketknight var kingofthehill var knightmate var berolina var losalamos var micro var capablanca var gothic var embassy var greatshatranj var courier var grand var opulent var omega var minishogi var shoshogi var shogi var torishogi var xiangqi
Debug - Windows
usiok 

> C:usi
> <C:Sjaak II version 1.3.1a (x86_64)
> <C:Type 'help' for a list of commands and help topics
> <C: 8r n b q k b n r 
> <C: 7p p p p p p p p 
> <C: 6                
> <C: 5                
> <C: 4                
> <C: 3                
> <C: 2P P P P P P P P 
> <C: 1R N B Q K B N R *
> <C:  a b c d e f g h 
> <C:#[Chess] 0w>

Tanuki WCSC 26 https://github.com/nodchip/tanuki-/releases/tag/WCSC26 - it seems that most applications  are suited to Haswell computers , but even  SSE42 GCC Lazy SMP.exe cannot be embedded> "not an USI engine", although a double mouse-click on this executable is functioning with Windows 7 SP1 64 bit - all extracted binaries are be located into the folder "Apery/bin"; Apery WCSC 26 cf. https://github.com/HiraokaTakuya/apery/releases
Debug - Windows

> C:usi
> C:usi
> <C:info string start setting eval table

WinBoard http://www.open-aurec.com/wbforum/viewtopic.php?f=19&t=51528 and
http://home.hccnet.nl/h.g.muller/shokidoki.html supports Shogi too. Have you tried out v4.8.0  in combination with your engine?

regards, ChessGUI

**Comment by HiraokaTakuya** [comment]
I don't know other USI engines's problems. Sorry.
